### ISSUE TITLE
Triggers Windows Defender on Windows 10

### ISSUE THREAD

**Issue by caccavale** [DarylPinto/shadow-cat#1]
![image](https://user-images.githubusercontent.com/6198074/50125354-73744500-0236-11e9-8ed3-bc253a17218c.png)

Any reason why the windows release in the README.md is triggering AV?

**Comment by DarylPinto** [comment]
Hi there,

I'm not really sure what's causing this. I can assure you nothing I've written is malicious, but if you prefer to take extra caution and refrain from using the program, then feel free.

On the other hand if you find anything information that could help identify why Windows Defender flags my program then please let me know. I'll begin investigating this right away.

**Comment by DarylPinto** [comment]
After researching `Occamy.C` and doing a little bit of re-reading through the code, it's possible that the AV is flagging Shadow Cat because of the following:

https://github.com/DarylPinto/shadow-cat/blob/53acc26132299ff5678b1a5081a02501a39eceaf/methods.py#L119-L130
https://github.com/DarylPinto/shadow-cat/blob/53acc26132299ff5678b1a5081a02501a39eceaf/obfuscate.py#L8-L12

What this function is doing is saving the user's Gfycat/Streamable login info to a file so that the program can use the username password after being closed re-opened without the user having to re-enter it every time.

When implementing this, to prevent users accidentally sending this info with others (by zipping Shadow Cat and sharing it) the file is encrypted with the *Hardware ID* of the computer, so that login info cannot be deciphered when opening the file on another computer. I don't know for certain, but it's possible that accessing the Hardware ID is seen as malicious by the AV software.

To fix this issue I'll save the login info in `appdata` instead of in the program directory. This means it's far less likely that a user will accidentally share their login info, and accessing the Hardware ID won't be necessary at all.
